### ISSUE TITLE
Formats with single quotes

### ISSUE THREAD

**Issue by edgarrmondragon** [gaborbernat/pyproject-fmt-rust#2]
**Describe the bug**

The Taplo formatter uses single quotes:

```toml
[project]
name='a-b'
```

**To Reproduce**

NA

**Expected behavior**

```toml
[project]
name="a-b"
```

**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04]
 - Browser [e.g. Firefox, Safari] (if applicable):

**Additional context**

* Blocked by https://github.com/tamasfe/taplo/issues/392
